/* File: greensmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Jan 30 11:16:47 2019
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *greens_error;
static PyObject *greens_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef struct {double r,i;} complex_double;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(greens_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#define pyobj_from_complex_double1(v) (PyComplex_FromDoubles(v.r,v.i))

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = greens_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = greens_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(testgreenfun01,TESTGREENFUN01)(double*,double*,double*,double*,double*,int*,int*);
extern void F_FUNC(rootslipunova,ROOTSLIPUNOVA)(double*,int*,double*,double*,double*);
extern void F_FUNC(greenlip,GREENLIP)(double*,double*,double*,double*,double*,double*,double*,int*,double*,double*);
extern void F_WRAPPEDFUNC_US(greenlip_f2,GREENLIP_F2)(complex_double*,double*,double*,double*,double*,double*,double*,double*,int*);
extern void F_WRAPPEDFUNC_US(greenlip_f,GREENLIP_F)(complex_double*,double*,double*,double*,double*,double*,double*,double*,int*);
extern void F_WRAPPEDFUNC(greenlipdicsmass,GREENLIPDICSMASS)(double*,double*,double*,double*,double*,double*,double*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* testgreenfun01 *******************************/
static char doc_f2py_rout_greens_testgreenfun01[] = "\
testgreenfun01(r_in,r_out,r_,n,t,n_root,n_r)\n\nWrapper for ``testgreenfun01``.\
\n\nParameters\n----------\n"
"r_in : input float\n"
"r_out : input float\n"
"r_ : input float\n"
"n : input float\n"
"t : input float\n"
"n_root : input int\n"
"n_r : input int";
/* extern void F_FUNC(testgreenfun01,TESTGREENFUN01)(double*,double*,double*,double*,double*,int*,int*); */
static PyObject *f2py_rout_greens_testgreenfun01(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double r_in = 0;
  PyObject *r_in_capi = Py_None;
  double r_out = 0;
  PyObject *r_out_capi = Py_None;
  double r_ = 0;
  PyObject *r__capi = Py_None;
  double n = 0;
  PyObject *n_capi = Py_None;
  double t = 0;
  PyObject *t_capi = Py_None;
  int n_root = 0;
  PyObject *n_root_capi = Py_None;
  int n_r = 0;
  PyObject *n_r_capi = Py_None;
  static char *capi_kwlist[] = {"r_in","r_out","r_","n","t","n_root","n_r",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:greens.testgreenfun01",\
    capi_kwlist,&r_in_capi,&r_out_capi,&r__capi,&n_capi,&t_capi,&n_root_capi,&n_r_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r_in */
    f2py_success = double_from_pyobj(&r_in,r_in_capi,"greens.testgreenfun01() 1st argument (r_in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_out */
    f2py_success = double_from_pyobj(&r_out,r_out_capi,"greens.testgreenfun01() 2nd argument (r_out) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_ */
    f2py_success = double_from_pyobj(&r_,r__capi,"greens.testgreenfun01() 3rd argument (r_) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = double_from_pyobj(&n,n_capi,"greens.testgreenfun01() 4th argument (n) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t */
    f2py_success = double_from_pyobj(&t,t_capi,"greens.testgreenfun01() 5th argument (t) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n_root */
    f2py_success = int_from_pyobj(&n_root,n_root_capi,"greens.testgreenfun01() 6th argument (n_root) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n_r */
    f2py_success = int_from_pyobj(&n_r,n_r_capi,"greens.testgreenfun01() 7th argument (n_r) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&r_in,&r_out,&r_,&n,&t,&n_root,&n_r);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of n_r*/
  /* End of cleaning variable n_r */
  } /*if (f2py_success) of n_root*/
  /* End of cleaning variable n_root */
  } /*if (f2py_success) of t*/
  /* End of cleaning variable t */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of r_*/
  /* End of cleaning variable r_ */
  } /*if (f2py_success) of r_out*/
  /* End of cleaning variable r_out */
  } /*if (f2py_success) of r_in*/
  /* End of cleaning variable r_in */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of testgreenfun01 ***************************/

/******************************* rootslipunova *******************************/
static char doc_f2py_rout_greens_rootslipunova[] = "\
rootslipunova(root,l,x_in,x_out,[n])\n\nWrapper for ``rootslipunova``.\
\n\nParameters\n----------\n"
"root : input rank-1 array('d') with bounds (n)\n"
"l : input float\n"
"x_in : input float\n"
"x_out : input float\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(root)";
/* extern void F_FUNC(rootslipunova,ROOTSLIPUNOVA)(double*,int*,double*,double*,double*); */
static PyObject *f2py_rout_greens_rootslipunova(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *root = NULL;
  npy_intp root_Dims[1] = {-1};
  const int root_Rank = 1;
  PyArrayObject *capi_root_tmp = NULL;
  int capi_root_intent = 0;
  PyObject *root_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  double l = 0;
  PyObject *l_capi = Py_None;
  double x_in = 0;
  PyObject *x_in_capi = Py_None;
  double x_out = 0;
  PyObject *x_out_capi = Py_None;
  static char *capi_kwlist[] = {"root","l","x_in","x_out","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|O:greens.rootslipunova",\
    capi_kwlist,&root_capi,&l_capi,&x_in_capi,&x_out_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable root */
  ;
  capi_root_intent |= F2PY_INTENT_IN;
  capi_root_tmp = array_from_pyobj(NPY_DOUBLE,root_Dims,root_Rank,capi_root_intent,root_capi);
  if (capi_root_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(greens_error,"failed in converting 1st argument `root' of greens.rootslipunova to C/Fortran array" );
  } else {
    root = (double *)(PyArray_DATA(capi_root_tmp));

  /* Processing variable l */
    f2py_success = double_from_pyobj(&l,l_capi,"greens.rootslipunova() 2nd argument (l) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x_in */
    f2py_success = double_from_pyobj(&x_in,x_in_capi,"greens.rootslipunova() 3rd argument (x_in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable x_out */
    f2py_success = double_from_pyobj(&x_out,x_out_capi,"greens.rootslipunova() 4th argument (x_out) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(root); else
    f2py_success = int_from_pyobj(&n,n_capi,"greens.rootslipunova() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(root)>=n,"len(root)>=n","1st keyword n","rootslipunova:n=%d",n) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(root,&n,&l,&x_in,&x_out);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(root)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of x_out*/
  /* End of cleaning variable x_out */
  } /*if (f2py_success) of x_in*/
  /* End of cleaning variable x_in */
  } /*if (f2py_success) of l*/
  /* End of cleaning variable l */
  if((PyObject *)capi_root_tmp!=root_capi) {
    Py_XDECREF(capi_root_tmp); }
  }  /*if (capi_root_tmp == NULL) ... else of root*/
  /* End of cleaning variable root */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of rootslipunova ****************************/

/********************************** greenlip **********************************/
static char doc_f2py_rout_greens_greenlip[] = "\
greenlip(r,r_,tv_in,r_in,r_out,n,k_i,sigma,mdot,[num])\n\nWrapper for ``greenlip``.\
\n\nParameters\n----------\n"
"r : input float\n"
"r_ : input float\n"
"tv_in : input float\n"
"r_in : input float\n"
"r_out : input float\n"
"n : input float\n"
"k_i : input rank-1 array('d') with bounds (num)\n"
"sigma : input float\n"
"mdot : input float\n"
"\nOther Parameters\n----------------\n"
"num : input int, optional\n    Default: len(k_i)";
/* extern void F_FUNC(greenlip,GREENLIP)(double*,double*,double*,double*,double*,double*,double*,int*,double*,double*); */
static PyObject *f2py_rout_greens_greenlip(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double r = 0;
  PyObject *r_capi = Py_None;
  double r_ = 0;
  PyObject *r__capi = Py_None;
  double tv_in = 0;
  PyObject *tv_in_capi = Py_None;
  double r_in = 0;
  PyObject *r_in_capi = Py_None;
  double r_out = 0;
  PyObject *r_out_capi = Py_None;
  double n = 0;
  PyObject *n_capi = Py_None;
  double *k_i = NULL;
  npy_intp k_i_Dims[1] = {-1};
  const int k_i_Rank = 1;
  PyArrayObject *capi_k_i_tmp = NULL;
  int capi_k_i_intent = 0;
  PyObject *k_i_capi = Py_None;
  int num = 0;
  PyObject *num_capi = Py_None;
  double sigma = 0;
  PyObject *sigma_capi = Py_None;
  double mdot = 0;
  PyObject *mdot_capi = Py_None;
  static char *capi_kwlist[] = {"r","r_","tv_in","r_in","r_out","n","k_i","sigma","mdot","num",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|O:greens.greenlip",\
    capi_kwlist,&r_capi,&r__capi,&tv_in_capi,&r_in_capi,&r_out_capi,&n_capi,&k_i_capi,&sigma_capi,&mdot_capi,&num_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r */
    f2py_success = double_from_pyobj(&r,r_capi,"greens.greenlip() 1st argument (r) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_ */
    f2py_success = double_from_pyobj(&r_,r__capi,"greens.greenlip() 2nd argument (r_) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tv_in */
    f2py_success = double_from_pyobj(&tv_in,tv_in_capi,"greens.greenlip() 3rd argument (tv_in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_in */
    f2py_success = double_from_pyobj(&r_in,r_in_capi,"greens.greenlip() 4th argument (r_in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_out */
    f2py_success = double_from_pyobj(&r_out,r_out_capi,"greens.greenlip() 5th argument (r_out) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = double_from_pyobj(&n,n_capi,"greens.greenlip() 6th argument (n) can't be converted to double");
  if (f2py_success) {
  /* Processing variable k_i */
  ;
  capi_k_i_intent |= F2PY_INTENT_IN;
  capi_k_i_tmp = array_from_pyobj(NPY_DOUBLE,k_i_Dims,k_i_Rank,capi_k_i_intent,k_i_capi);
  if (capi_k_i_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(greens_error,"failed in converting 7th argument `k_i' of greens.greenlip to C/Fortran array" );
  } else {
    k_i = (double *)(PyArray_DATA(capi_k_i_tmp));

  /* Processing variable sigma */
    f2py_success = double_from_pyobj(&sigma,sigma_capi,"greens.greenlip() 8th argument (sigma) can't be converted to double");
  if (f2py_success) {
  /* Processing variable mdot */
    f2py_success = double_from_pyobj(&mdot,mdot_capi,"greens.greenlip() 9th argument (mdot) can't be converted to double");
  if (f2py_success) {
  /* Processing variable num */
  if (num_capi == Py_None) num = len(k_i); else
    f2py_success = int_from_pyobj(&num,num_capi,"greens.greenlip() 1st keyword (num) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(k_i)>=num,"len(k_i)>=num","1st keyword num","greenlip:num=%d",num) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&r,&r_,&tv_in,&r_in,&r_out,&n,k_i,&num,&sigma,&mdot);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(k_i)>=num)*/
  } /*if (f2py_success) of num*/
  /* End of cleaning variable num */
  } /*if (f2py_success) of mdot*/
  /* End of cleaning variable mdot */
  } /*if (f2py_success) of sigma*/
  /* End of cleaning variable sigma */
  if((PyObject *)capi_k_i_tmp!=k_i_capi) {
    Py_XDECREF(capi_k_i_tmp); }
  }  /*if (capi_k_i_tmp == NULL) ... else of k_i*/
  /* End of cleaning variable k_i */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of r_out*/
  /* End of cleaning variable r_out */
  } /*if (f2py_success) of r_in*/
  /* End of cleaning variable r_in */
  } /*if (f2py_success) of tv_in*/
  /* End of cleaning variable tv_in */
  } /*if (f2py_success) of r_*/
  /* End of cleaning variable r_ */
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of greenlip ******************************/

/******************************** greenlip_f2 ********************************/
static char doc_f2py_rout_greens_greenlip_f2[] = "\
greenlip_f2 = greenlip_f2(r,r_,fv_in,r_in,r_out,n,k_i,[num])\n\nWrapper for ``greenlip_f2``.\
\n\nParameters\n----------\n"
"r : input float\n"
"r_ : input float\n"
"fv_in : input float\n"
"r_in : input float\n"
"r_out : input float\n"
"n : input float\n"
"k_i : input rank-1 array('d') with bounds (num)\n"
"\nOther Parameters\n----------------\n"
"num : input int, optional\n    Default: len(k_i)\n"
"\nReturns\n-------\n"
"greenlip_f2 : complex";
/* extern void F_WRAPPEDFUNC_US(greenlip_f2,GREENLIP_F2)(complex_double*,double*,double*,double*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout_greens_greenlip_f2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(complex_double*,double*,double*,double*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  complex_double greenlip_f2;
  PyObject *greenlip_f2_capi = Py_None;
  double r = 0;
  PyObject *r_capi = Py_None;
  double r_ = 0;
  PyObject *r__capi = Py_None;
  double fv_in = 0;
  PyObject *fv_in_capi = Py_None;
  double r_in = 0;
  PyObject *r_in_capi = Py_None;
  double r_out = 0;
  PyObject *r_out_capi = Py_None;
  double n = 0;
  PyObject *n_capi = Py_None;
  double *k_i = NULL;
  npy_intp k_i_Dims[1] = {-1};
  const int k_i_Rank = 1;
  PyArrayObject *capi_k_i_tmp = NULL;
  int capi_k_i_intent = 0;
  PyObject *k_i_capi = Py_None;
  int num = 0;
  PyObject *num_capi = Py_None;
  static char *capi_kwlist[] = {"r","r_","fv_in","r_in","r_out","n","k_i","num",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:greens.greenlip_f2",\
    capi_kwlist,&r_capi,&r__capi,&fv_in_capi,&r_in_capi,&r_out_capi,&n_capi,&k_i_capi,&num_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r */
    f2py_success = double_from_pyobj(&r,r_capi,"greens.greenlip_f2() 1st argument (r) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_ */
    f2py_success = double_from_pyobj(&r_,r__capi,"greens.greenlip_f2() 2nd argument (r_) can't be converted to double");
  if (f2py_success) {
  /* Processing variable fv_in */
    f2py_success = double_from_pyobj(&fv_in,fv_in_capi,"greens.greenlip_f2() 3rd argument (fv_in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_in */
    f2py_success = double_from_pyobj(&r_in,r_in_capi,"greens.greenlip_f2() 4th argument (r_in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_out */
    f2py_success = double_from_pyobj(&r_out,r_out_capi,"greens.greenlip_f2() 5th argument (r_out) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = double_from_pyobj(&n,n_capi,"greens.greenlip_f2() 6th argument (n) can't be converted to double");
  if (f2py_success) {
  /* Processing variable k_i */
  ;
  capi_k_i_intent |= F2PY_INTENT_IN;
  capi_k_i_tmp = array_from_pyobj(NPY_DOUBLE,k_i_Dims,k_i_Rank,capi_k_i_intent,k_i_capi);
  if (capi_k_i_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(greens_error,"failed in converting 7th argument `k_i' of greens.greenlip_f2 to C/Fortran array" );
  } else {
    k_i = (double *)(PyArray_DATA(capi_k_i_tmp));

  /* Processing variable greenlip_f2 */
  /* Processing variable num */
  if (num_capi == Py_None) num = len(k_i); else
    f2py_success = int_from_pyobj(&num,num_capi,"greens.greenlip_f2() 1st keyword (num) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(k_i)>=num,"len(k_i)>=num","1st keyword num","greenlip_f2:num=%d",num) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&greenlip_f2,&r,&r_,&fv_in,&r_in,&r_out,&n,k_i,&num);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  greenlip_f2_capi = pyobj_from_complex_double1(greenlip_f2);
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",greenlip_f2_capi);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(k_i)>=num)*/
  } /*if (f2py_success) of num*/
  /* End of cleaning variable num */
  /* End of cleaning variable greenlip_f2 */
  if((PyObject *)capi_k_i_tmp!=k_i_capi) {
    Py_XDECREF(capi_k_i_tmp); }
  }  /*if (capi_k_i_tmp == NULL) ... else of k_i*/
  /* End of cleaning variable k_i */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of r_out*/
  /* End of cleaning variable r_out */
  } /*if (f2py_success) of r_in*/
  /* End of cleaning variable r_in */
  } /*if (f2py_success) of fv_in*/
  /* End of cleaning variable fv_in */
  } /*if (f2py_success) of r_*/
  /* End of cleaning variable r_ */
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of greenlip_f2 *****************************/

/********************************* greenlip_f *********************************/
static char doc_f2py_rout_greens_greenlip_f[] = "\
greenlip_f = greenlip_f(r,r_,fv_in,r_in,r_out,n,k_i,[num])\n\nWrapper for ``greenlip_f``.\
\n\nParameters\n----------\n"
"r : input float\n"
"r_ : input float\n"
"fv_in : input float\n"
"r_in : input float\n"
"r_out : input float\n"
"n : input float\n"
"k_i : input rank-1 array('d') with bounds (num)\n"
"\nOther Parameters\n----------------\n"
"num : input int, optional\n    Default: len(k_i)\n"
"\nReturns\n-------\n"
"greenlip_f : complex";
/* extern void F_WRAPPEDFUNC_US(greenlip_f,GREENLIP_F)(complex_double*,double*,double*,double*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout_greens_greenlip_f(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(complex_double*,double*,double*,double*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  complex_double greenlip_f;
  PyObject *greenlip_f_capi = Py_None;
  double r = 0;
  PyObject *r_capi = Py_None;
  double r_ = 0;
  PyObject *r__capi = Py_None;
  double fv_in = 0;
  PyObject *fv_in_capi = Py_None;
  double r_in = 0;
  PyObject *r_in_capi = Py_None;
  double r_out = 0;
  PyObject *r_out_capi = Py_None;
  double n = 0;
  PyObject *n_capi = Py_None;
  double *k_i = NULL;
  npy_intp k_i_Dims[1] = {-1};
  const int k_i_Rank = 1;
  PyArrayObject *capi_k_i_tmp = NULL;
  int capi_k_i_intent = 0;
  PyObject *k_i_capi = Py_None;
  int num = 0;
  PyObject *num_capi = Py_None;
  static char *capi_kwlist[] = {"r","r_","fv_in","r_in","r_out","n","k_i","num",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO|O:greens.greenlip_f",\
    capi_kwlist,&r_capi,&r__capi,&fv_in_capi,&r_in_capi,&r_out_capi,&n_capi,&k_i_capi,&num_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r */
    f2py_success = double_from_pyobj(&r,r_capi,"greens.greenlip_f() 1st argument (r) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_ */
    f2py_success = double_from_pyobj(&r_,r__capi,"greens.greenlip_f() 2nd argument (r_) can't be converted to double");
  if (f2py_success) {
  /* Processing variable fv_in */
    f2py_success = double_from_pyobj(&fv_in,fv_in_capi,"greens.greenlip_f() 3rd argument (fv_in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_in */
    f2py_success = double_from_pyobj(&r_in,r_in_capi,"greens.greenlip_f() 4th argument (r_in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_out */
    f2py_success = double_from_pyobj(&r_out,r_out_capi,"greens.greenlip_f() 5th argument (r_out) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = double_from_pyobj(&n,n_capi,"greens.greenlip_f() 6th argument (n) can't be converted to double");
  if (f2py_success) {
  /* Processing variable k_i */
  ;
  capi_k_i_intent |= F2PY_INTENT_IN;
  capi_k_i_tmp = array_from_pyobj(NPY_DOUBLE,k_i_Dims,k_i_Rank,capi_k_i_intent,k_i_capi);
  if (capi_k_i_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(greens_error,"failed in converting 7th argument `k_i' of greens.greenlip_f to C/Fortran array" );
  } else {
    k_i = (double *)(PyArray_DATA(capi_k_i_tmp));

  /* Processing variable greenlip_f */
  /* Processing variable num */
  if (num_capi == Py_None) num = len(k_i); else
    f2py_success = int_from_pyobj(&num,num_capi,"greens.greenlip_f() 1st keyword (num) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(k_i)>=num,"len(k_i)>=num","1st keyword num","greenlip_f:num=%d",num) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&greenlip_f,&r,&r_,&fv_in,&r_in,&r_out,&n,k_i,&num);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  greenlip_f_capi = pyobj_from_complex_double1(greenlip_f);
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",greenlip_f_capi);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(k_i)>=num)*/
  } /*if (f2py_success) of num*/
  /* End of cleaning variable num */
  /* End of cleaning variable greenlip_f */
  if((PyObject *)capi_k_i_tmp!=k_i_capi) {
    Py_XDECREF(capi_k_i_tmp); }
  }  /*if (capi_k_i_tmp == NULL) ... else of k_i*/
  /* End of cleaning variable k_i */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of r_out*/
  /* End of cleaning variable r_out */
  } /*if (f2py_success) of r_in*/
  /* End of cleaning variable r_in */
  } /*if (f2py_success) of fv_in*/
  /* End of cleaning variable fv_in */
  } /*if (f2py_success) of r_*/
  /* End of cleaning variable r_ */
  } /*if (f2py_success) of r*/
  /* End of cleaning variable r */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of greenlip_f *****************************/

/****************************** greenlipdicsmass ******************************/
static char doc_f2py_rout_greens_greenlipdicsmass[] = "\
greenlipdicsmass = greenlipdicsmass(r_,t,r_in,r_out,n,k_i,[num])\n\nWrapper for ``greenlipdicsmass``.\
\n\nParameters\n----------\n"
"r_ : input float\n"
"t : input float\n"
"r_in : input float\n"
"r_out : input float\n"
"n : input float\n"
"k_i : input rank-1 array('d') with bounds (num)\n"
"\nOther Parameters\n----------------\n"
"num : input int, optional\n    Default: len(k_i)\n"
"\nReturns\n-------\n"
"greenlipdicsmass : float";
/* extern void F_WRAPPEDFUNC(greenlipdicsmass,GREENLIPDICSMASS)(double*,double*,double*,double*,double*,double*,double*,int*); */
static PyObject *f2py_rout_greens_greenlipdicsmass(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double greenlipdicsmass = 0;
  double r_ = 0;
  PyObject *r__capi = Py_None;
  double t = 0;
  PyObject *t_capi = Py_None;
  double r_in = 0;
  PyObject *r_in_capi = Py_None;
  double r_out = 0;
  PyObject *r_out_capi = Py_None;
  double n = 0;
  PyObject *n_capi = Py_None;
  double *k_i = NULL;
  npy_intp k_i_Dims[1] = {-1};
  const int k_i_Rank = 1;
  PyArrayObject *capi_k_i_tmp = NULL;
  int capi_k_i_intent = 0;
  PyObject *k_i_capi = Py_None;
  int num = 0;
  PyObject *num_capi = Py_None;
  static char *capi_kwlist[] = {"r_","t","r_in","r_out","n","k_i","num",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|O:greens.greenlipdicsmass",\
    capi_kwlist,&r__capi,&t_capi,&r_in_capi,&r_out_capi,&n_capi,&k_i_capi,&num_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r_ */
    f2py_success = double_from_pyobj(&r_,r__capi,"greens.greenlipdicsmass() 1st argument (r_) can't be converted to double");
  if (f2py_success) {
  /* Processing variable t */
    f2py_success = double_from_pyobj(&t,t_capi,"greens.greenlipdicsmass() 2nd argument (t) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_in */
    f2py_success = double_from_pyobj(&r_in,r_in_capi,"greens.greenlipdicsmass() 3rd argument (r_in) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_out */
    f2py_success = double_from_pyobj(&r_out,r_out_capi,"greens.greenlipdicsmass() 4th argument (r_out) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = double_from_pyobj(&n,n_capi,"greens.greenlipdicsmass() 5th argument (n) can't be converted to double");
  if (f2py_success) {
  /* Processing variable k_i */
  ;
  capi_k_i_intent |= F2PY_INTENT_IN;
  capi_k_i_tmp = array_from_pyobj(NPY_DOUBLE,k_i_Dims,k_i_Rank,capi_k_i_intent,k_i_capi);
  if (capi_k_i_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(greens_error,"failed in converting 6th argument `k_i' of greens.greenlipdicsmass to C/Fortran array" );
  } else {
    k_i = (double *)(PyArray_DATA(capi_k_i_tmp));

  /* Processing variable greenlipdicsmass */
  /* Processing variable num */
  if (num_capi == Py_None) num = len(k_i); else
    f2py_success = int_from_pyobj(&num,num_capi,"greens.greenlipdicsmass() 1st keyword (num) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(k_i)>=num,"len(k_i)>=num","1st keyword num","greenlipdicsmass:num=%d",num) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&greenlipdicsmass,&r_,&t,&r_in,&r_out,&n,k_i,&num);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",greenlipdicsmass);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(k_i)>=num)*/
  } /*if (f2py_success) of num*/
  /* End of cleaning variable num */
  /* End of cleaning variable greenlipdicsmass */
  if((PyObject *)capi_k_i_tmp!=k_i_capi) {
    Py_XDECREF(capi_k_i_tmp); }
  }  /*if (capi_k_i_tmp == NULL) ... else of k_i*/
  /* End of cleaning variable k_i */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of r_out*/
  /* End of cleaning variable r_out */
  } /*if (f2py_success) of r_in*/
  /* End of cleaning variable r_in */
  } /*if (f2py_success) of t*/
  /* End of cleaning variable t */
  } /*if (f2py_success) of r_*/
  /* End of cleaning variable r_ */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of greenlipdicsmass **************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"testgreenfun01",-1,{{-1}},0,(char *)F_FUNC(testgreenfun01,TESTGREENFUN01),(f2py_init_func)f2py_rout_greens_testgreenfun01,doc_f2py_rout_greens_testgreenfun01},
  {"rootslipunova",-1,{{-1}},0,(char *)F_FUNC(rootslipunova,ROOTSLIPUNOVA),(f2py_init_func)f2py_rout_greens_rootslipunova,doc_f2py_rout_greens_rootslipunova},
  {"greenlip",-1,{{-1}},0,(char *)F_FUNC(greenlip,GREENLIP),(f2py_init_func)f2py_rout_greens_greenlip,doc_f2py_rout_greens_greenlip},
  {"greenlip_f2",-1,{{-1}},0,(char *)F_WRAPPEDFUNC_US(greenlip_f2,GREENLIP_F2),(f2py_init_func)f2py_rout_greens_greenlip_f2,doc_f2py_rout_greens_greenlip_f2},
  {"greenlip_f",-1,{{-1}},0,(char *)F_WRAPPEDFUNC_US(greenlip_f,GREENLIP_F),(f2py_init_func)f2py_rout_greens_greenlip_f,doc_f2py_rout_greens_greenlip_f},
  {"greenlipdicsmass",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(greenlipdicsmass,GREENLIPDICSMASS),(f2py_init_func)f2py_rout_greens_greenlipdicsmass,doc_f2py_rout_greens_greenlipdicsmass},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "greens",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_greens(void) {
#else
#define RETVAL
PyMODINIT_FUNC initgreens(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = greens_module = PyModule_Create(&moduledef);
#else
  m = greens_module = Py_InitModule("greens", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module greens (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'greens' is auto-generated with f2py (version:2).\nFunctions:\n"
"  testgreenfun01(r_in,r_out,r_,n,t,n_root,n_r)\n"
"  rootslipunova(root,l,x_in,x_out,n=len(root))\n"
"  greenlip(r,r_,tv_in,r_in,r_out,n,k_i,sigma,mdot,num=len(k_i))\n"
"  greenlip_f2 = greenlip_f2(r,r_,fv_in,r_in,r_out,n,k_i,num=len(k_i))\n"
"  greenlip_f = greenlip_f(r,r_,fv_in,r_in,r_out,n,k_i,num=len(k_i))\n"
"  greenlipdicsmass = greenlipdicsmass(r_,t,r_in,r_out,n,k_i,num=len(k_i))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  greens_error = PyErr_NewException ("greens.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));




    {
      extern complex_double F_FUNC_US(greenlip_f2,GREENLIP_F2)(void);
      PyObject* o = PyDict_GetItemString(d,"greenlip_f2");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(greenlip_f2,GREENLIP_F2),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("greenlip_f2"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("greenlip_f2"));
#endif
    }
    

    {
      extern complex_double F_FUNC_US(greenlip_f,GREENLIP_F)(void);
      PyObject* o = PyDict_GetItemString(d,"greenlip_f");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC_US(greenlip_f,GREENLIP_F),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("greenlip_f"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("greenlip_f"));
#endif
    }
    

    {
      extern double F_FUNC(greenlipdicsmass,GREENLIPDICSMASS)(void);
      PyObject* o = PyDict_GetItemString(d,"greenlipdicsmass");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(greenlipdicsmass,GREENLIPDICSMASS),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("greenlipdicsmass"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("greenlipdicsmass"));
#endif
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"greens");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
